"""Add unique constraints for idempotency

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002_add_share_token'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_commit_eval_sha', 'commits', ['evaluation_id', 'sha'])
    op.create_unique_constraint('uq_pr_eval_number', 'pull_requests', ['evaluation_id', 'pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pr_eval_number', 'pull_requests', type_='unique')
    op.drop_constraint('uq_commit_eval_sha', 'commits', type_='unique')
    # ### end Alembic commands ###
